config/routes.rb
Rails.application.routes.draw do
  resources :external_incomes
  resources :expenses
  resources :providers
  resources :payments
  resources :orders do
    collection do
      get 'active_orders'
      get 'closed_orders'
    end
    member do
      get 'add_ordered_product'
      get 'print'
      get 'view_ordered_product'
      put 'add_product'
      put 'close'
      put 'add_discount'
      put 'remove_discount'
      delete 'remove_ordered_product'
    end
  end
  devise_for :users
  resources :products do
    collection do
      post 'add_product_items'
      delete 'destroy_product_item'
    end
  end
  resources :items
  resources :categories
  resources :working_stations
  resources :stores
  resources :reports do
    collection do
      get 'daily_report'
      get 'monthly_report'
      get 'closes'
      post 'daily_close'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :store
  has_many :products
  has_one_attached :image

  scope :for_store, -> (store_id) { where(store_id: store_id) }
end

app/models/close.rb
class Close < ApplicationRecord
  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/expense.rb
class Expense < ApplicationRecord
  enum source: [ :card, :cash ]

  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/external_income.rb
class ExternalIncome < ApplicationRecord
  enum payment_method: [ :card, :cash ]
  enum source: [ :uber_eats, :didi_food, :rappi, :other ]

  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
  belongs_to :provider
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :store
  has_many :order_products
  has_one :payment

  enum order_type: [ :local, :togo, :delivery ]
  enum status: [ :open, :closed ]
  enum delivery_app: [ :ours, :rappi, :eats ]
  enum discount_type: [ :percentage, :direct ]

  scope :open, -> { where(status: :open) }

  def subtotal
    subtotal = 0
    order_products.each do |op|
      subtotal += op.product.price * op.quantity
    end
    subtotal
  end

  def total
    return subtotal unless discount
    
    if percentage? 
      return (subtotal - (subtotal * discount / 100.0)).ceil
    elsif direct?
      return subtotal - discount
    end
  end

  def close(payment_method)
    self.closed!
    Payment.create(order_id: self.id, total: total, payment_method: payment_method.to_i)
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def price
    quantity * product.price
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  
  enum discount_type: [ :percentage, :direct ]
  enum payment_method: [ :card, :cash, :transfer ]

  scope :for_date, -> (date_start, date_end) { where('created_at > ? and created_at < ?', date_start, date_end) }
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :store
  belongs_to :working_station
  has_many :product_items
  has_one_attached :image

  scope :for_store, -> (store_id) { where(store_id: store_id) }
  scope :available, -> { where(available: true) }
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :item
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :user_permissions
  has_many :permissions, through: :user_permissions

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def can(ability)
    self.permissions.where(ability: ability).any?
  end
end

app/models/user_ability.rb
class UserAbility < ApplicationRecord
  belongs_to :user
  belongs_to :ability
end

app/models/user_permission.rb
class UserPermission < ApplicationRecord
  belongs_to :user
  belongs_to :permission
end

app/models/working_station.rb
class WorkingStation < ApplicationRecord
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def payment_params
      params.require(:payment).permit(:order_id, :total, :discount, :discount_type, :payment_method)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment) do |form| %>
  <% if payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :order_id, style: "display: block" %>
    <%= form.text_field :order_id %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.label :discount, style: "display: block" %>
    <%= form.text_field :discount %>
  </div>

  <div>
    <%= form.label :discount_type, style: "display: block" %>
    <%= form.number_field :discount_type %>
  </div>

  <div>
    <%= form.label :payment_method, style: "display: block" %>
    <%= form.number_field :payment_method %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/_payment.html.erb
<div id="<%= dom_id payment %>">
  <p>
    <strong>Order:</strong>
    <%= payment.order_id %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= payment.total %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= payment.discount %>
  </p>

  <p>
    <strong>Discount type:</strong>
    <%= payment.discount_type %>
  </p>

  <p>
    <strong>Payment method:</strong>
    <%= payment.payment_method %>
  </p>

</div>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Show this payment", @payment %> |
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Payments</h1>

<div id="payments">
  <% @payments.each do |payment| %>
    <%= render payment %>
    <p>
      <%= link_to "Show this payment", payment %>
    </p>
  <% end %>
</div>

<%= link_to "New payment", new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<%= render "form", payment: @payment %>

<br>

<div>
  <%= link_to "Back to payments", payments_path %>
</div>

app/views/payments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @payment %>

<div>
  <%= link_to "Edit this payment", edit_payment_path(@payment) %> |
  <%= link_to "Back to payments", payments_path %>

  <%= button_to "Destroy this payment", @payment, method: :delete %>
</div>