config/routes.rb
Rails.application.routes.draw do
  resources :external_incomes
  resources :expenses
  resources :providers
  resources :payments
  resources :orders do
    collection do
      get 'active_orders'
      get 'closed_orders'
    end
    member do
      get 'add_ordered_product'
      get 'print'
      get 'view_ordered_product'
      put 'add_product'
      put 'close'
      put 'add_discount'
      put 'remove_discount'
      delete 'remove_ordered_product'
    end
  end
  devise_for :users
  resources :products do
    collection do
      post 'add_product_items'
      delete 'destroy_product_item'
    end
  end
  resources :items
  resources :categories
  resources :working_stations
  resources :stores
  resources :reports do
    collection do
      get 'daily_report'
      get 'monthly_report'
      get 'closes'
      post 'daily_close'
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/ability.rb
class Ability < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :store
  has_many :products
  has_one_attached :image

  scope :for_store, -> (store_id) { where(store_id: store_id) }
end

app/models/close.rb
class Close < ApplicationRecord
  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/expense.rb
class Expense < ApplicationRecord
  enum source: [ :card, :cash ]

  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/external_income.rb
class ExternalIncome < ApplicationRecord
  enum payment_method: [ :card, :cash ]
  enum source: [ :uber_eats, :didi_food, :rappi, :other ]

  scope :for_date, -> (date_start, date_end) { where('date >= ? and date <= ?', date_start, date_end) }
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :store
  belongs_to :provider
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :store
  has_many :order_products
  has_one :payment

  enum order_type: [ :local, :togo, :delivery ]
  enum status: [ :open, :closed ]
  enum delivery_app: [ :ours, :rappi, :eats ]
  enum discount_type: [ :percentage, :direct ]

  scope :open, -> { where(status: :open) }

  def subtotal
    subtotal = 0
    order_products.each do |op|
      subtotal += op.product.price * op.quantity
    end
    subtotal
  end

  def total
    return subtotal unless discount
    
    if percentage? 
      return (subtotal - (subtotal * discount / 100.0)).ceil
    elsif direct?
      return subtotal - discount
    end
  end

  def close(payment_method)
    self.closed!
    Payment.create(order_id: self.id, total: total, payment_method: payment_method.to_i)
  end
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :order
  belongs_to :product

  def price
    quantity * product.price
  end
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
  
  enum discount_type: [ :percentage, :direct ]
  enum payment_method: [ :card, :cash, :transfer ]

  scope :for_date, -> (date_start, date_end) { where('created_at > ? and created_at < ?', date_start, date_end) }
end

app/models/permission.rb
class Permission < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :store
  belongs_to :working_station
  has_many :product_items
  has_one_attached :image

  scope :for_store, -> (store_id) { where(store_id: store_id) }
  scope :available, -> { where(available: true) }
end

app/models/product_item.rb
class ProductItem < ApplicationRecord
  belongs_to :product
  belongs_to :item
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :store
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, # :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :user_permissions
  has_many :permissions, through: :user_permissions

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def can(ability)
    self.permissions.where(ability: ability).any?
  end
end

app/models/user_ability.rb
class UserAbility < ApplicationRecord
  belongs_to :user
  belongs_to :ability
end

app/models/user_permission.rb
class UserPermission < ApplicationRecord
  belongs_to :user
  belongs_to :permission
end

app/models/working_station.rb
class WorkingStation < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[ show edit update destroy ]

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
    @category.store_id = current_user.store_id

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path, notice: "Nueva categoría creada con éxito." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @categories = Category.where(store_id: current_user.store_id)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :store_id, :image)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Store:</strong>
    <%= category.store_id %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :store_id, style: "display: block" %>
    <%= form.text_field :store_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/_modals.html.erb
<!--begin::Modal - New category-->
<div class="modal fade" id="kt_modal_new_category" tabindex="-1" aria-hidden="true">
  <!--begin::Modal dialog-->
  <div class="modal-dialog modal-dialog-centered mw-650px">
    <!--begin::Modal content-->
    <div class="modal-content">
      <!--begin::Form-->
      <%= form_with scope: :category, url: "/categories", method: :post do |form| %>
        <!--begin::Modal header-->
        <div class="modal-header" id="kt_modal_new_category_header">
          <!--begin::Modal title-->
          <h2>Agregar Nueva Categoría</h2>
          <!--end::Modal title-->
          <!--begin::Close-->
          <div class="btn btn-sm btn-icon btn-active-color-primary" data-bs-dismiss="modal">
            <i class="ki-duotone ki-cross fs-1">
              <span class="path1"></span>
              <span class="path2"></span>
            </i>
          </div>
          <!--end::Close-->
        </div>
        <!--end::Modal header-->
        <!--begin::Modal body-->
        <div class="modal-body py-10 px-lg-17">
          <!--begin::Scroll-->
          <div class="scroll-y me-n7 pe-7" id="kt_modal_new_item_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_new_item_header" data-kt-scroll-wrappers="#kt_modal_new_item_scroll" data-kt-scroll-offset="300px">
            <!--begin::Input group-->
            <div class="d-flex flex-column mb-5 fv-row">
              <!--begin::Label-->
              <label class="required fs-5 fw-semibold mb-2">Nombre</label>
              <!--end::Label-->
              <!--begin::Input-->
              <%= form.text_field :name, class: "form-control form-control-solid" %>
              <!--end::Input-->
            </div>
            <!--end::Input group-->
          </div>
          <!--end::Scroll-->
        </div>
        <!--end::Modal body-->
        <!--begin::Modal footer-->
        <div class="modal-footer flex-center">
          <!--begin::Button-->
          <button type="reset" id="kt_modal_new_item_cancel" class="btn btn-light me-3" data-bs-dismiss="modal">Cancelar</button>
          <!--end::Button-->
          <!--begin::Button-->
          <button type="submit" id="kt_modal_new_item_submit" class="btn btn-primary">
            <span>Guardar</span>
          </button>
          <!--end::Button-->
        </div>
        <!--end::Modal footer-->
      <% end %>
      <!--end::Form-->
    </div>
  </div>
</div>
<!--end::Modal - New Item-->

app/views/categories/edit.html.erb
<%= turbo_frame_tag "modal" do %>
  <!--begin::Modal - New Item-->
  <div class="modal fade show" id="kt_modal_new_item" tabindex="-1" aria-hidden="true" style="display:block;">
    <!--begin::Modal dialog-->
    <div class="modal-dialog modal-dialog-centered mw-650px">
      <!--begin::Modal content-->
      <div class="modal-content">
        <!--begin::Form-->
        <%= form_with(model: @category) do |form| %>
          <!--begin::Modal header-->
          <div class="modal-header" id="kt_modal_new_item_header">
            <!--begin::Modal title-->
            <h2>Editar Categoría</h2>
            <!--end::Modal title-->
            <!--begin::Close-->
            <%= link_to "#", data: { controller: "modals", action: "modals#close" }, class: "btn btn-sm btn-icon btn-active-color-primary" do %>
              <i class="ki-duotone ki-cross fs-1">
                <span class="path1"></span>
                <span class="path2"></span>
              </i>
            <% end %>
            <!--end::Close-->
          </div>
          <!--end::Modal header-->
          <!--begin::Modal body-->
          <div class="modal-body py-10 px-lg-17">
            <!--begin::Scroll-->
            <div class="scroll-y me-n7 pe-7" id="kt_modal_new_item_scroll" data-kt-scroll="true" data-kt-scroll-activate="{default: false, lg: true}" data-kt-scroll-max-height="auto" data-kt-scroll-dependencies="#kt_modal_new_item_header" data-kt-scroll-wrappers="#kt_modal_new_item_scroll" data-kt-scroll-offset="300px">
              <!--begin::Input group-->
              <div class="d-flex flex-column mb-5 fv-row">
                <!--begin::Label-->
                <label class="required fs-5 fw-semibold mb-2">Nombre</label>
                <!--end::Label-->
                <!--begin::Input-->
                <%= form.text_field :name, class: "form-control form-control-solid" %>
                <!--end::Input-->
              </div>
              <!--end::Input group-->
              <!--begin::Input group-->
              <div class="d-flex flex-column mb-5 fv-row">
                <!--begin::Label-->
                <label class="required fs-5 fw-semibold mb-2">Imagen de Categoría</label>
                <!--end::Label-->
                <!--begin::Image input-->
                <div class="image-input image-input-empty image-input-outline image-input-placeholder mb-3" data-kt-image-input="true">
                  <!--begin::Preview existing avatar-->
                  <div class="image-input-wrapper w-150px h-150px" style="background-image: <%= @category.image.blank? ? 'url(assets/media/svg/files/blank-image.svg)' : url_for(@category.image) %>"></div>
                  <!--end::Preview existing avatar-->
                  <!--begin::Label-->
                  <label class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="change" data-bs-toggle="tooltip" title="Change avatar">
                    <i class="ki-duotone ki-pencil fs-7">
                      <span class="path1"></span>
                      <span class="path2"></span>
                    </i>
                    <!--begin::Inputs-->
                    <%= form.file_field :image, accept: "image/png,image/jpg,image/jpeg" %>
                    <input type="hidden" name="avatar_remove" />
                    <!--end::Inputs-->
                  </label>
                  <!--end::Label-->
                  <!--begin::Cancel-->
                  <span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="cancel" data-bs-toggle="tooltip" title="Cancel avatar">
                    <i class="ki-duotone ki-cross fs-2">
                      <span class="path1"></span>
                      <span class="path2"></span>
                    </i>
                  </span>
                  <!--end::Cancel-->
                  <!--begin::Remove-->
                  <span class="btn btn-icon btn-circle btn-active-color-primary w-25px h-25px bg-body shadow" data-kt-image-input-action="remove" data-bs-toggle="tooltip" title="Remove avatar">
                    <i class="ki-duotone ki-cross fs-2">
                      <span class="path1"></span>
                      <span class="path2"></span>
                    </i>
                  </span>
                  <!--end::Remove-->
                </div>
                <!--end::Image input-->
              </div>
              <!--end::Input group-->
            </div>
            <!--end::Scroll-->
          </div>
          <!--end::Modal body-->
          <!--begin::Modal footer-->
          <div class="modal-footer flex-center">
            <!--begin::Button-->
            <%= button_to "Cancelar", "#", data: {
              controller: "modals",
              action: "modals#close",
            }, class: "btn btn-light me-3" %>
            <!--end::Button-->
            <!--begin::Button-->
            <button type="submit" id="kt_modal_new_item_submit" class="btn btn-primary">
              <span>Guardar</span>
            </button>
            <!--end::Button-->
          </div>
          <!--end::Modal footer-->
        <% end %>
        <!--end::Form-->
      </div>
    </div>
  </div>
  <!--end::Modal - New Item-->
<% end %>

app/views/categories/index.html.erb
<!--begin::Toolbar-->
<div id="kt_app_toolbar" class="app-toolbar py-3 py-lg-6">
  <!--begin::Toolbar container-->
  <div id="kt_app_toolbar_container" class="app-container container-fluid d-flex flex-stack">
    <!--begin::Page title-->
    <div class="page-title d-flex flex-column justify-content-center flex-wrap me-3">
      <!--begin::Title-->
      <h1 class="page-heading d-flex text-dark fw-bold fs-3 flex-column justify-content-center my-0">Categorías</h1>
      <!--end::Title-->
      <!--begin::Breadcrumb-->
      <ul class="breadcrumb breadcrumb-separatorless fw-semibold fs-7 my-0 pt-1">
        <!--begin::Item-->
        <li class="breadcrumb-item text-muted">
          <a href="../../demo1/dist/index.html" class="text-muted text-hover-primary">Administración</a>
        </li>
        <!--end::Item-->
        <!--begin::Item-->
        <!--
        <li class="breadcrumb-item">
          <span class="bullet bg-gray-400 w-5px h-2px"></span>
        </li>
        -->
        <!--end::Item-->
        <!--begin::Item-->
        <!--<li class="breadcrumb-item text-muted">Dashboards</li>-->
        <!--end::Item-->
      </ul>
      <!--end::Breadcrumb-->
    </div>
    <!--end::Page title-->
    <!--begin::Actions-->
    <div class="d-flex align-items-center gap-2 gap-lg-3">
      <!--begin::Secondary button-->
      <!--<a href="#" class="btn btn-sm fw-bold bg-body btn-color-gray-700 btn-active-color-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_create_app">Rollover</a>-->
      <!--end::Secondary button-->
      <!--begin::Primary button-->
      <!--<a href="#" class="btn btn-sm fw-bold btn-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_new_item">Nuevo Insumo</a>-->
      <!--end::Primary button-->
    </div>
    <!--end::Actions-->
  </div>
  <!--end::Toolbar container-->
</div>
<!--end::Toolbar-->
<!--begin::Content-->
<div id="kt_app_content" class="app-content flex-column-fluid">
  <!--begin::Content container-->
  <div id="kt_app_content_container" class="app-container container-fluid">
    <!--begin::Card-->
    <div class="card card-flush">
      <!--begin::Card header-->
      <div class="card-header mt-6">
        <!--begin::Card title-->
        <div class="card-title">
          <!--begin::Search-->
          <div class="d-flex align-items-center position-relative my-1 me-5">
            <i class="ki-duotone ki-magnifier fs-3 position-absolute ms-5">
              <span class="path1"></span>
              <span class="path2"></span>
            </i>
            <input type="text" data-kt-permissions-table-filter="search" class="form-control form-control-solid w-250px ps-13" placeholder="Buscar Categoría" />
          </div>
          <!--end::Search-->
        </div>
        <!--end::Card title-->
        <!--begin::Card toolbar-->
        <div class="card-toolbar">
          <!--begin::Button-->
          <button type="button" class="btn btn-light-primary" data-bs-toggle="modal" data-bs-target="#kt_modal_new_category">
          <i class="ki-duotone ki-plus-square fs-3">
            <span class="path1"></span>
            <span class="path2"></span>
            <span class="path3"></span>
          </i>Nueva Categoría</button>
          <!--end::Button-->
        </div>
        <!--end::Card toolbar-->
      </div>
      <!--end::Card header-->
      <!--begin::Card body-->
      <div class="card-body pt-0">
        <!--begin::Table-->
        <table class="table align-middle table-row-dashed fs-6 gy-5 mb-0" id="kt_permissions_table">
          <thead>
            <tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
              <th class="">Nombre</th>
              <th class="text-end">Acciones</th>
            </tr>
          </thead>
          <tbody class="fw-semibold text-gray-600">
            <% @categories.each do |category| %>
            <tr>
              <td>
                <div class="d-flex align-items-center">
                  <div class="symbol symbol-50px me-5">
                    <span class="symbol-label bg-light">
                      <img src="<%= category.image.blank? ? 'assets/media/svg/food-icons/coffee.svg' : url_for(category.image) %>" class="h-75 align-self-end" alt="">
                    </span>
                  </div>
                  <div class="d-flex justify-content-start flex-column">
                    <a href="#" class="text-dark fw-bold text-hover-primary mb-1 fs-6"><%= category.name.capitalize %></a>
                  </div>
                </div>
              </td>
              <td class="text-end">
                <%= link_to edit_category_path(category), data: { turbo_frame: "modal" }, class: "btn btn-icon btn-bg-light btn-active-color-primary btn-sm me-1" do %>
                <i class="ki-duotone ki-pencil fs-2">
                  <span class="path1"></span>
                  <span class="path2"></span>
                </i>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <!--end::Table-->
      </div>
      <!--end::Card body-->
    </div>
    <!--end::Card-->
  </div>
  <!--end::Content container-->
</div>
<!--end::Content-->

<%= render "categories/modals" %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>